//! User-level systemd automation for `lastcall enable` / `lastcall disable`.
//!
//! Nothing here runs as root, and nothing here installs or removes the binary.

use std::fs;
use std::path::PathBuf;
use std::process::Command;

use anyhow::{anyhow, bail, Context, Result};
use chrono::{DateTime, Duration, Utc};

use crate::config::Config;
use crate::usage::ProviderKind;

const SERVICE: &str = "lastcall.service";
const TIMER: &str = "lastcall.timer";
const MARKER: &str = "# Generated by lastcall. Recreated by `lastcall enable`.";

pub fn unit_dir() -> Result<PathBuf> {
    Ok(dirs::config_dir()
        .ok_or_else(|| anyhow!("no XDG config directory"))?
        .join("systemd")
        .join("user"))
}

pub fn service_unit(exe: &str) -> String {
    format!(
        "{MARKER}\n\
         [Unit]\n\
         Description=Lastcall AI quota check\n\
         \n\
         [Service]\n\
         Type=oneshot\n\
         ExecStart={exe} --notify\n"
    )
}

pub fn timer_unit(interval: Duration) -> String {
    let seconds = interval.num_seconds();
    format!(
        "{MARKER}\n\
         [Unit]\n\
         Description=Lastcall AI quota reminder\n\
         \n\
         [Timer]\n\
         OnStartupSec=2m\n\
         OnUnitActiveSec={seconds}s\n\
         Persistent=true\n\
         \n\
         [Install]\n\
         WantedBy=timers.target\n"
    )
}

/// Never poll more often than this, however tight the configured window is.
const MIN_INTERVAL: Duration = Duration::minutes(15);
/// Never poll less often than this, however wide the configured window is.
const MAX_INTERVAL: Duration = Duration::hours(12);
/// The tightest `before` a timer can actually service, given `MIN_INTERVAL`.
pub const MIN_BEFORE: Duration = Duration::minutes(30);

/// Derive the polling interval from the enabled providers' windows.
///
/// A run must land inside the `before` window to notify at all, so poll at
/// roughly half the tightest window. With the 24h default that is the familiar
/// 12h tick; a `before = "1h"` config gets a 30m tick instead of silently
/// never firing.
pub fn poll_interval(config: &Config) -> Duration {
    (tightest_window(config) / 2).clamp(MIN_INTERVAL, MAX_INTERVAL)
}

/// The tightest window among enabled providers, defaulting to the maximum when
/// every provider is disabled.
fn tightest_window(config: &Config) -> Duration {
    enabled_kinds(config)
        .map(|kind| config.rule_for(kind).before_reset)
        .min()
        .unwrap_or(MAX_INTERVAL * 2)
}

fn enabled_kinds(config: &Config) -> impl Iterator<Item = ProviderKind> + '_ {
    [ProviderKind::Claude, ProviderKind::Codex]
        .into_iter()
        .filter(|kind| config.is_enabled(*kind))
}

/// Refuse to arm a timer that cannot possibly fire inside the configured
/// window. Interactive use is unrestricted; only automation needs this.
fn ensure_serviceable(config: &Config) -> Result<()> {
    if !enabled_kinds(config).any(|_| true) {
        bail!(
            "no providers are enabled, so there would be nothing to check; \
             run `lastcall config --claude --enable` (or `--codex`) first"
        );
    }

    let tightest = tightest_window(config);
    if tightest < MIN_BEFORE {
        bail!(
            "`before` must be at least {} for automatic notifications \
             (checks cannot run more often than every {}); it is currently {}",
            crate::usage::format_span(MIN_BEFORE),
            crate::usage::format_span(MIN_INTERVAL),
            crate::usage::format_span(tightest)
        );
    }
    Ok(())
}

/// Returns the polling interval that was installed.
pub fn enable(config: &Config) -> Result<Duration> {
    let interval = install(config)?;
    // Run once immediately so the user does not wait for the first tick.
    systemctl(&["start", SERVICE])?;
    Ok(interval)
}

/// Write the units and (re-)arm the timer, without running a check.
///
/// Used both by `enable` and by a configuration change, which must update the
/// baked-in polling interval but has no business sending notifications.
pub fn install(config: &Config) -> Result<Duration> {
    ensure_systemd()?;
    ensure_serviceable(config)?;
    crate::notify::ensure_available()?;

    let exe = std::env::current_exe()
        .context("resolving the lastcall binary path")?
        .to_string_lossy()
        .to_string();
    let interval = poll_interval(config);

    let dir = unit_dir()?;
    fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;
    write_unit(&dir.join(SERVICE), &service_unit(&exe))?;
    write_unit(&dir.join(TIMER), &timer_unit(interval))?;

    systemctl(&["daemon-reload"])?;
    systemctl(&["enable", "--now", TIMER])?;
    Ok(interval)
}

/// What the systemd side of automation is currently doing.
#[derive(Debug, Default, PartialEq)]
pub struct Status {
    pub active: bool,
    /// When the background check last finished, if it ever has.
    pub last_run: Option<DateTime<Utc>>,
    /// Whether that run exited cleanly.
    pub last_ok: Option<bool>,
}

impl Status {
    /// `OnUnitActiveSec` counts from the last activation, so the next check is
    /// simply the last one plus the interval.
    pub fn next_run(&self, interval: Duration) -> Option<DateTime<Utc>> {
        self.last_run.map(|last| last + interval)
    }
}

pub fn status() -> Status {
    let active = is_active();
    let (last_run, last_ok) = match show(
        SERVICE,
        &["ExecMainExitTimestamp", "ExecMainStatus", "Result"],
    ) {
        Some(properties) => {
            let last_run = properties
                .iter()
                .find_map(|(key, value)| (key == "ExecMainExitTimestamp").then_some(value))
                .and_then(|value| parse_unix_property(value));
            let ok = properties
                .iter()
                .find_map(|(key, value)| (key == "Result").then_some(value))
                .map(|value| value == "success");
            (last_run, last_run.and(ok))
        }
        None => (None, None),
    };

    Status {
        active,
        last_run,
        last_ok,
    }
}

/// Read `systemctl show` properties as key/value pairs.
fn show(unit: &str, properties: &[&str]) -> Option<Vec<(String, String)>> {
    let output = Command::new("systemctl")
        .arg("--user")
        .arg("show")
        .arg(unit)
        .arg("--timestamp=unix")
        .args(
            properties
                .iter()
                .map(|property| format!("--property={property}")),
        )
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    Some(
        String::from_utf8_lossy(&output.stdout)
            .lines()
            .filter_map(|line| line.split_once('='))
            .map(|(key, value)| (key.to_string(), value.to_string()))
            .collect(),
    )
}

/// `--timestamp=unix` renders instants as `@1787669200`; an unset property is
/// empty.
fn parse_unix_property(value: &str) -> Option<DateTime<Utc>> {
    let seconds: i64 = value.strip_prefix('@')?.parse().ok()?;
    DateTime::from_timestamp(seconds, 0)
}

/// Whether automatic notifications are currently armed *by lastcall*.
///
/// Both halves matter: an active timer we did not generate is none of our
/// business, and our unit file lying around inactive is not something to
/// re-arm behind the user's back.
pub fn is_active() -> bool {
    let ours = unit_dir()
        .ok()
        .and_then(|dir| fs::read_to_string(dir.join(TIMER)).ok())
        .is_some_and(|contents| contents.starts_with(MARKER));

    ours && Command::new("systemctl")
        .arg("--user")
        .args(["is-active", "--quiet", TIMER])
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

/// Write a generated unit, refusing to clobber a file we did not generate.
fn write_unit(path: &std::path::Path, contents: &str) -> Result<()> {
    match fs::read_to_string(path) {
        Ok(existing) if !existing.starts_with(MARKER) => bail!(
            "{} already exists and was not generated by lastcall; \
             move it aside and try again",
            path.display()
        ),
        Ok(_) => {}
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
        Err(err) => return Err(err).with_context(|| format!("reading {}", path.display())),
    }
    fs::write(path, contents).with_context(|| format!("writing {}", path.display()))
}

pub fn disable() -> Result<()> {
    ensure_systemd()?;

    // Best effort: a half-installed timer must still be removable.
    let _ = systemctl(&["disable", "--now", TIMER]);

    let dir = unit_dir()?;
    for unit in [TIMER, SERVICE] {
        let path = dir.join(unit);
        match fs::read_to_string(&path) {
            Ok(contents) if contents.starts_with(MARKER) => {
                fs::remove_file(&path).with_context(|| format!("removing {}", path.display()))?
            }
            Ok(_) => eprintln!(
                "Left {} in place: it was not generated by lastcall.",
                path.display()
            ),
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
            Err(err) => return Err(err).with_context(|| format!("reading {}", path.display())),
        }
    }

    systemctl(&["daemon-reload"])?;
    Ok(())
}

fn ensure_systemd() -> Result<()> {
    if !cfg!(target_os = "linux") {
        bail!("automatic notifications are Linux-only in v0.1");
    }
    if std::env::var_os("XDG_RUNTIME_DIR").is_none() {
        bail!("no XDG_RUNTIME_DIR: this does not look like a systemd user session");
    }
    let found = Command::new("sh")
        .arg("-c")
        .arg("command -v systemctl")
        .output()
        .context("looking for systemctl")?
        .status
        .success();
    if !found {
        bail!("systemctl was not found; a systemd user session is required");
    }
    Ok(())
}

fn systemctl(args: &[&str]) -> Result<()> {
    let output = Command::new("systemctl")
        .arg("--user")
        .args(args)
        .output()
        .with_context(|| format!("running systemctl --user {}", args.join(" ")))?;

    if !output.status.success() {
        bail!(
            "systemctl --user {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn units_are_marked_and_wired_correctly() {
        let service = service_unit("/home/u/.cargo/bin/lastcall");
        assert!(service.starts_with(MARKER));
        assert!(service.contains("Type=oneshot"));
        assert!(service.contains("ExecStart=/home/u/.cargo/bin/lastcall --notify"));

        let timer = timer_unit(Duration::hours(12));
        assert!(timer.starts_with(MARKER));
        assert!(timer.contains("OnUnitActiveSec=43200s"));
        assert!(timer.contains("Persistent=true"));
        assert!(timer.contains("WantedBy=timers.target"));
    }

    /// The default 24h window keeps the familiar 12h tick.
    #[test]
    fn the_default_config_polls_every_twelve_hours() {
        assert_eq!(poll_interval(&Config::default()), Duration::hours(12));
    }

    /// A tight window must not be able to fall between two ticks.
    #[test]
    fn a_tight_window_polls_more_often() {
        let mut config = Config::default();
        config.claude.rule.before_reset = Duration::hours(1);
        assert_eq!(poll_interval(&config), Duration::minutes(30));
    }

    #[test]
    fn the_interval_is_clamped_at_both_ends() {
        let mut config = Config::default();
        config.claude.rule.before_reset = Duration::days(30);
        config.codex.rule.before_reset = Duration::days(30);
        assert_eq!(poll_interval(&config), MAX_INTERVAL);
    }

    /// A disabled provider must not drag the interval down.
    #[test]
    fn a_disabled_provider_does_not_affect_the_interval() {
        let mut config = Config::default();
        config.claude.rule.before_reset = Duration::hours(1);
        config.claude.enabled = false;
        assert_eq!(poll_interval(&config), Duration::hours(12));
    }

    /// A window the timer cannot service is refused, not silently missed.
    #[test]
    fn an_unserviceable_window_is_rejected() {
        let mut config = Config::default();
        config.codex.rule.before_reset = Duration::minutes(1);
        let err = ensure_serviceable(&config).unwrap_err().to_string();
        assert!(err.contains("at least 30m"), "{err}");

        config.codex.rule.before_reset = MIN_BEFORE;
        assert!(ensure_serviceable(&config).is_ok());
    }

    #[test]
    fn disabling_the_tight_provider_makes_it_serviceable_again() {
        let mut config = Config::default();
        config.codex.rule.before_reset = Duration::minutes(1);
        config.codex.enabled = false;
        assert!(ensure_serviceable(&config).is_ok());
    }

    /// Arming a timer with nothing to check is refused, not silently accepted.
    #[test]
    fn no_enabled_providers_is_refused() {
        let mut config = Config::default();
        config.claude.enabled = false;
        config.codex.enabled = false;
        let err = ensure_serviceable(&config).unwrap_err().to_string();
        assert!(err.contains("no providers are enabled"), "{err}");
    }

    #[test]
    fn next_run_follows_the_last_one() {
        let last = DateTime::from_timestamp(1_787_669_200, 0).unwrap();
        let status = Status {
            active: true,
            last_run: Some(last),
            last_ok: Some(true),
        };
        assert_eq!(
            status.next_run(Duration::hours(12)),
            Some(last + Duration::hours(12))
        );
        assert_eq!(Status::default().next_run(Duration::hours(12)), None);
    }

    #[test]
    fn parses_the_unix_timestamp_property() {
        assert_eq!(
            parse_unix_property("@1787669200"),
            DateTime::from_timestamp(1_787_669_200, 0)
        );
        assert_eq!(parse_unix_property(""), None);
        assert_eq!(parse_unix_property("Tue 2026-08-25 16:14:19 CEST"), None);
    }

    #[test]
    fn write_unit_refuses_to_clobber_a_foreign_file() {
        let dir = std::env::temp_dir().join(format!("lastcall-units-{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        let path = dir.join("lastcall.timer");

        fs::write(&path, "[Timer]\nOnCalendar=daily\n").unwrap();
        assert!(write_unit(&path, &timer_unit(Duration::hours(12))).is_err());
        assert!(fs::read_to_string(&path).unwrap().contains("OnCalendar"));

        // Our own generated unit is replaced without complaint.
        fs::write(&path, timer_unit(Duration::hours(6))).unwrap();
        write_unit(&path, &timer_unit(Duration::hours(12))).unwrap();
        assert!(fs::read_to_string(&path)
            .unwrap()
            .contains("OnUnitActiveSec=43200s"));

        fs::remove_dir_all(&dir).unwrap();
    }
}
